version: "3"
services:
  mongodb:
    container_name: mongo-container
    image: mongo:5.0.2
    restart: unless-stopped
    volumes:
      - db:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    user: root
    image: node:20
    working_dir: /usr/src/tech-challenge-produce
    command: bash -c "npm install && npm run debug"
    environment:
      - MONGO_URL=mongodb://mongo:27017/tech-challenge-produce
    volumes:
      - ./dist/:/usr/src/tech-challenge-produce/dist/
      - ./package.json:/usr/src/tech-challenge-produce/package.json
    ports:
      - "5050:5050"
      - "9222:9222"
    depends_on:
      - mongodb
volumes:
  db: