version: '3'
services:
  api:
    image: node:20
    container_name: tech_challenge_produce_api 
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: bash -c "npm i && npm run build && npm run start"
    ports:
      - 3333:3333
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/order_status
      - PORT=3333
      - DOMAIN=http://localhost
      - DATABASE=order_status
      - URL_MICROSERVICE_PAYMENT=
  mongodb:
    container_name:  tech_challenge_mongodb
    restart: unless-stopped
    image: mongo:latest
    ports:
      - 27017:27017