apiVersion: apps/v1
kind: Deployment
metadata:
  name: controladorproducao-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: controladorproducao-app
  template:
    metadata:
      labels:
        app: controladorproducao-app
    spec:
      containers:
        - name: controladorproducao-app
          image: __CONTROLADOR_PEDIDO_IMAGE_NAME__
          env:
            - name: URL_MICROSERVICE_PAYMENT
              value: http://controladorpagamento:5004
            - name: MONGO_URI
              value: mongodb+srv://admin:terraform@tc-db-produce.6vjyeov.mongodb.net/tech_challenge_db
          ports:
            - containerPort: 3333
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: controladorproducao-app
spec:
  selector:
    app: controladorproducao-app
  ports:
    - protocol: TCP
      port: 3333
      targetPort: 3333
  type: LoadBalancer
