name: Build and Test

on:
  push:
    branches:
      - feat/deploy-project

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Unit Tests
        run: npm run test

      - name: Prepare coverage report in markdown
        uses: fingerprintjs/action-coverage-report-md@v1
        id: coverage
        
      - name: Add coverage comment to the PR 
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: ${{ steps.coverage.outputs.markdownReport }}