name: Terraform MongoDB Atlas - Create

on:
  push:
    branches:
      - feat/deploy-project

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Generate terraform.tfvars.json
        run: |
          echo '{
            "public_key": "${{ secrets.ATLAS_PUBLIC_KEY }}",
            "private_key": "${{ secrets.ATLAS_PRIVATE_KEY }}",
            "project_id": "${{ secrets.ATLAS_PROJECT_ID }}",
            "mongodb_atlas_database_username": "${{ secrets.MONGODB_USERNAME }}",
            "mongodb_atlas_database_password": "${{ secrets.MONGODB_PASSWORD }}"
          }' > terraform.tfvars.json

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -var-file=terraform.tfvars.json -no-color

      - name: Terraform Apply
        id: apply
        run: terraform apply -var-file=terraform.tfvars.json -auto-approve

      - name: Create MongoDB Connection String
        id: mongodb_connection
        run: |
          echo terraform output db_cn_string
          output=$(terraform output db_cn_string)
          chmod +x ./modify_mongodb_string.sh
          connection_string=$(./modify_mongodb_string.sh ${{ secrets.ATLAS_PROJECT_ID }} ${{ secrets.MONGODB_USERNAME }} ${{ secrets.MONGODB_PASSWORD }})
          echo "MONGODB_CONN_STRING=$connection_string" >> $GITHUB_ENV
        shell: bash

      - name: Use MongoDB Connection String
        run: |
          echo "MongoDB Connection String: $MONGODB_CONN_STRING"