name: Terraform MongoDB Atlas - Create
on: 
    workflow_dispatch

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
            gh variable list
            gh variable set MONGODB_CONN_STRING --body "Set from workflow"
            gh variable list
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}