name: Terraform MongoDB Atlas - Create

on:
  push:
    branches:
      - feat/deploy-project

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Generate terraform.tfvars.json
        run: |
          echo '{
            "public_key": "${{ secrets.ATLAS_PUBLIC_KEY }}",
            "private_key": "${{ secrets.ATLAS_PRIVATE_KEY }}",
            "project_id": "${{ secrets.ATLAS_PROJECT_ID }}",
            "mongodb_atlas_database_username": "${{ secrets.MONGODB_USERNAME }}",
            "mongodb_atlas_database_password": "${{ secrets.MONGODB_PASSWORD }}"
          }' > terraform.tfvars.json

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -var-file=terraform.tfvars.json -no-color

      - name: Terraform Apply
        id: apply
        run: terraform apply -var-file=terraform.tfvars.json -auto-approve

      - name: Terraform Output
        id: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo $(terraform output -raw db_cn_string)
          variable_name="MONGODB_CONN_STRING"
          connection_string="$(terraform output -raw db_cn_string)

          repo_owner="owner"
          repo_name="repository"

          # Atualiza a variável de repositório usando a API do GitHub
          curl -X PATCH \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$repo_owner/$repo_name/actions/secrets/$variable_name" \
            -d "{\"encrypted_value\": \"$(echo -n $connection_string | openssl enc -base64)\", \"key_id\": null}""